In [39]:
import numpy as np


In [40]:
arr_1 = np.array([1,2,3,4,5]) 
print(arr_1)

arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


# numpy vs list


In [41]:
arr_list = [1, 2, 3, 4]
print("array:", arr_list * 2)

arr_3 = np.array([1, 2, 4, 5])
print(arr_3 * 2)

import time 
start = time.time()
arr_list = [i*2 for i in range(100000)]
print(time.time() - start)

start = time.time()
arr_np = np.arange(100000)*2
print(time.time() - start)



array: [1, 2, 3, 4, 1, 2, 3, 4]
[ 2  4  8 10]
0.008456945419311523
0.0007638931274414062


### Creating Array fron scratch 

In [42]:
zeros  = np.zeros((2,5))
print("Zeros Array: ",zeros)

ones  = np.ones((3,5))
print("ones Array: ",ones)

full = np.full((2,2),8)
print("full Array: ",full)

random = np.random.random((2,3))
print("random Array: ",random)

sequence = np.arange(0,11,2)
print("Sequence Array: ",sequence)

Zeros Array:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones Array:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full Array:  [[8 8]
 [8 8]]
random Array:  [[0.0838403  0.51276897 0.62793925]
 [0.97088154 0.81064329 0.66557536]]
Sequence Array:  [ 0  2  4  6  8 10]


### Vector , matrix, tensor


In [43]:
vector = np.array([1,2,3])
print("v",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("m",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[1,2],[4,5]]])
print("t",tensor)
                    

v [1 2 3]
m [[1 2 3]
 [4 5 6]]
t [[[1 2]
  [3 4]]

 [[1 2]
  [4 5]]]


### properties of array


In [44]:

arr = np.array([[1,2,3],
                [2,2,2],
                [3,3,3]])

print("Size", arr.size)
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Dtype", arr.dtype)




Size 9
Shape (3, 3)
Dimension 2
Dtype int64


### Array Reshapping

In [46]:
arr = np.arange(20)
print("Original Array:", arr)

reshaped = arr.reshape((4,5))
print("Reshaped Array:\n", reshaped)

flattened = reshaped.flatten() # return copy
print("Flattened Array:", flattened)

raveled = reshaped.ravel() # return view , insted of copt
print("Raveled Array:", raveled)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### Transpose


In [48]:
transpose = reshaped.T
print(transpose)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
