### Numpy Array Operation


In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Indexing:", [2,8])
print("Indexing With Steps:", [1,9,2])
print("Negative Indexing:", [-4])

Basic Indexing: [2, 8]
Indexing With Steps: [1, 9, 2]
Negative Indexing: [-4]


In [3]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element:", arr_2d[1,2])
print("Entire Row:", arr_2d[1])
print("Specific Column:", arr_2d[:,2])

Specific Element: 6
Entire Row: [4 5 6]
Specific Column: [3 6 9]


### Sorting

In [9]:
arr_unsorted = np.array([1,3,2,42,1,54,6])
print("Sorted Array",np.sort(arr_unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array by column",np.sort(arr_2d_unsorted,axis=0))



Sorted Array [ 1  1  2  3  6 42 54]
Sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


In [10]:
arr_2d = np.array([
    [3, 1, 5],
    [1, 2, 4],
    [2, 3, 6]
])

# Sort rows based on the 3rd column (index 2)
sorted_arr = arr_2d[arr_2d[:, 2].argsort()]

print(sorted_arr)

[[1 2 4]
 [3 1 5]
 [2 3 6]]


## Filter

In [11]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[number % 2 ==0]
print(even_number)

[ 2  4  6  8 10]


## Filter with MASK

In [13]:
mask = number > 5
print(number[mask])
print(mask)

[ 6  7  8  9 10]
[False False False False False  True  True  True  True  True]


## Fancy indexing VS np.where()

### Fancy indexing means selecting elements using a list or array of indices.
### finds indices where a condition is True.

In [21]:
incides = [1,2,3,4]
print(number[incides])

where_num = np.where(number > 5)
print(where_num)
print(number[where_num])

[2 3 4 5]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [22]:
conditional = np.where(number>5,number*3,number)
print(conditional)


[ 1  2  3  4  5 18 21 24 27 30]


### Add and Remove Data 

In [26]:
arr_a = np.array([1,2,3,4])
arr_b = np.array([5,6,7,8])

combine = np.concatenate((arr_b,arr_b))
print(combine)



[5 6 7 8 5 6 7 8]


## Array compatbility

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatbility shape:", a.shape == b.shape)
print("compatbility shape:", c.shape == b.shape)
print("compatbility shape:", c.shape == a.shape)




compatbility shape: True
compatbility shape: True
compatbility shape: True


In [32]:
real = np.array([[1,2,3],[4,5,6]])
new_row = np.array([1,4,7])

with_new_row = np.vstack((real,new_row))
print("original", real)
print("new", with_new_row)

original [[1 2 3]
 [4 5 6]]
new [[1 2 3]
 [4 5 6]
 [1 4 7]]


In [39]:

new_col = np.array([[1,4],[3,4]])

with_new_col = np.hstack((real,new_col))
print("new", with_new_col)

new [[1 2 3 1 4]
 [4 5 6 3 4]]


In [40]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([5, 6, 7, 8])

print(np.hstack((arr_a, arr_b)))

[1 2 3 5 6 7 8]


## Delete

In [41]:
arr = np.array([10, 20, 30, 40, 50])

result = np.delete(arr, 2)

print(result)

[10 20 40 50]
