### Numpy Sort

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[18, 48, 88, 39],
       [82, 93, 34, 67],
       [22, 73, 95, 34],
       [14, 50, 79,  7],
       [39, 28, 15, 31],
       [51, 12, 48,  1]])

In [4]:
np.sort(a)

array([30, 34, 37, 38, 42, 45, 45, 57, 58, 76, 78, 83, 84, 88, 98])

In [5]:
#reverse 
np.sort(a)[::-1]

array([98, 88, 84, 83, 78, 76, 58, 57, 45, 45, 42, 38, 37, 34, 30])

In [6]:
# by row
np.sort(b,axis=1)

array([[18, 39, 48, 88],
       [34, 67, 82, 93],
       [22, 34, 73, 95],
       [ 7, 14, 50, 79],
       [15, 28, 31, 39],
       [ 1, 12, 48, 51]])

In [7]:
# By column
np.sort(b,axis=0)

array([[14, 12, 15,  1],
       [18, 28, 34,  7],
       [22, 48, 48, 31],
       [39, 50, 79, 34],
       [51, 73, 88, 39],
       [82, 93, 95, 67]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [8]:
np.append(a,200)

array([ 34,  84,  78,  37,  38,  45,  42,  30,  76,  98,  57,  83,  45,
        88,  58, 200])

In [9]:
b

array([[18, 48, 88, 39],
       [82, 93, 34, 67],
       [22, 73, 95, 34],
       [14, 50, 79,  7],
       [39, 28, 15, 31],
       [51, 12, 48,  1]])

In [16]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[18., 48., 88., 39.,  1.],
       [82., 93., 34., 67.,  1.],
       [22., 73., 95., 34.,  1.],
       [14., 50., 79.,  7.,  1.],
       [39., 28., 15., 31.,  1.],
       [51., 12., 48.,  1.,  1.]])

In [17]:
np.append(b, np.ones((b.shape[0], 1)))

array([18., 48., 88., 39., 82., 93., 34., 67., 22., 73., 95., 34., 14.,
       50., 79.,  7., 39., 28., 15., 31., 51., 12., 48.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [22]:
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[18.        , 48.        , 88.        , 39.        ,  0.71371202],
       [82.        , 93.        , 34.        , 67.        ,  0.97939998],
       [22.        , 73.        , 95.        , 34.        ,  0.69677884],
       [14.        , 50.        , 79.        ,  7.        ,  0.49756939],
       [39.        , 28.        , 15.        , 31.        ,  0.52706915],
       [51.        , 12.        , 48.        ,  1.        ,  0.31715856]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [23]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [24]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

### With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [27]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [28]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.where

In [29]:
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [30]:
np.where(a>50)

(array([ 1,  2,  8,  9, 10, 11, 13, 14]),)

In [31]:
np.where(a>50,0,a)

array([34,  0,  0, 37, 38, 45, 42, 30,  0,  0,  0,  0, 45,  0,  0])

In [32]:
np.where(a % 2 == 0, 0 ,a)

array([ 0,  0,  0, 37,  0, 45,  0,  0,  0,  0, 57, 83, 45,  0,  0])

# np.argmax

## The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [33]:
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [36]:
np.argmax(a)

np.int64(9)

In [37]:
b

array([[18, 48, 88, 39],
       [82, 93, 34, 67],
       [22, 73, 95, 34],
       [14, 50, 79,  7],
       [39, 28, 15, 31],
       [51, 12, 48,  1]])

In [38]:
np.argmax(b,axis = 0)

array([1, 1, 2, 1])

In [39]:
np.argmax(b,axis = 1)

array([2, 1, 2, 2, 0, 0])

In [40]:
np.argmin(a)

np.int64(7)

# CumSum

## numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [41]:
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [42]:
np.cumsum(a)

array([ 34, 118, 196, 233, 271, 316, 358, 388, 464, 562, 619, 702, 747,
       835, 893])

In [43]:
b

array([[18, 48, 88, 39],
       [82, 93, 34, 67],
       [22, 73, 95, 34],
       [14, 50, 79,  7],
       [39, 28, 15, 31],
       [51, 12, 48,  1]])

In [44]:
np.cumsum(b,axis=1)

array([[ 18,  66, 154, 193],
       [ 82, 175, 209, 276],
       [ 22,  95, 190, 224],
       [ 14,  64, 143, 150],
       [ 39,  67,  82, 113],
       [ 51,  63, 111, 112]])

In [45]:
np.cumsum(b,axis=0)

array([[ 18,  48,  88,  39],
       [100, 141, 122, 106],
       [122, 214, 217, 140],
       [136, 264, 296, 147],
       [175, 292, 311, 178],
       [226, 304, 359, 179]])

In [47]:
np.cumprod(a)

array([                  34,                 2856,               222768,
                    8242416,            313211808,          14094531360,
               591970317120,       17759109513600,     1349692323033600,
         132269847657292800,  7539381316465689600, -1420649239472518144,
       -8588983555134661632,   485954170241392640, -8708146273418330112])

# np.percentile

In [48]:
a


array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [49]:
np.percentile(a,50)

np.float64(57.0)

In [50]:
np.median(a)

np.float64(57.0)

# np.histogram

In [51]:
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [52]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 0, 0, 4, 3, 2, 0, 2, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

In [54]:
salary = np.array([20000,40000,250000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[ 1.        , -0.16522107],
       [-0.16522107,  1.        ]])

# np.isin
## to search multiple iteam at once

In [55]:
a


array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [58]:
items = [10,20,30,40.50,60,70,80,90,100]
a[np.isin(a,items)]

array([30])

# np.flip  reverse the order

In [59]:
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [65]:
np.flip(a)

array([ 58,  88,  45,  83,  57,  98,  76,  30,  42,  45,  38,  37,  78,
       530, 110])

In [61]:
np.flip(b)

array([[ 1, 48, 12, 51],
       [31, 15, 28, 39],
       [ 7, 79, 50, 14],
       [34, 95, 73, 22],
       [67, 34, 93, 82],
       [39, 88, 48, 18]])

# np.put
## The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [62]:
a

array([34, 84, 78, 37, 38, 45, 42, 30, 76, 98, 57, 83, 45, 88, 58])

In [63]:
np.put(a,[0,1],[110,530])

In [64]:
a

array([110, 530,  78,  37,  38,  45,  42,  30,  76,  98,  57,  83,  45,
        88,  58])

# np.delete

In [66]:
a

array([110, 530,  78,  37,  38,  45,  42,  30,  76,  98,  57,  83,  45,
        88,  58])

In [67]:
np.delete(a,[0,2,4])

array([530,  37,  45,  42,  30,  76,  98,  57,  83,  45,  88,  58])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [68]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.intersect1d(m,n)

array([3, 4, 5])

In [74]:
np.setdiff1d(m,n)
# whic are in a but not in b

array([1, 2])

In [71]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [72]:
m[np.in1d(m,1)]

/var/folders/dg/ycg49qvj1cb1ms3x_67_676r0000gn/T/ipykernel_5040/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])